FROM node:18-alpine as builder

WORKDIR /app/web/

COPY package*.json ./

RUN mkdir -p ./node_modules
RUN chown node:node ./node_modules
RUN mkdir -p ./node_modules/.cache && chmod -R 777 ./node_modules/.cache

RUN npm install

COPY . ./
RUN npm run build

#Stage 2
FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/web/dist .
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
